pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Travis CI - Pull Request
      - status-success=Flutter Ci / Test and Analyze
      - '#approved-reviews-by>=1'
    actions:
      merge:
        method: squash

  - name: automatic merge on CI success
    conditions:
      - status-success=Travis CI - Pull Request
      - status-success=Flutter Ci / Test and Analyze
      - author=Leocardoso94
    actions:
      merge:
        method: squash
