on: push

name: Flutter Ci

jobs:
  build:
    name: Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter doctor
      - run: flutter analyze
      - run: flutter test
